/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const CashTransferCategory = IDL.Variant({
  'needToPay' : IDL.Null,
  'repay' : IDL.Null,
  'family' : IDL.Null,
});
export const MedicalCategory = IDL.Variant({
  'hospital' : IDL.Null,
  'medicine' : IDL.Null,
});
export const Category = IDL.Variant({
  'tea' : IDL.Null,
  'cashTransfer' : CashTransferCategory,
  'coolDrink' : IDL.Null,
  'petrol' : IDL.Null,
  'food' : IDL.Null,
  'trip' : IDL.Null,
  'others' : IDL.Null,
  'recharge' : IDL.Null,
  'bikeRepair' : IDL.Null,
  'fruits' : IDL.Null,
  'shopping' : IDL.Null,
  'medical' : MedicalCategory,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const Expense = IDL.Record({
  'id' : IDL.Nat,
  'subCategory' : IDL.Opt(IDL.Text),
  'date' : IDL.Text,
  'note' : IDL.Opt(IDL.Text),
  'repayName' : IDL.Opt(IDL.Text),
  'category' : Category,
  'amount' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addExpense' : IDL.Func(
      [
        IDL.Text,
        Category,
        IDL.Opt(IDL.Text),
        IDL.Nat,
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
      ],
      [IDL.Nat],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteExpense' : IDL.Func([IDL.Nat], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getExpenses' : IDL.Func([], [IDL.Vec(Expense)], ['query']),
  'getExpensesByDate' : IDL.Func([IDL.Text], [IDL.Vec(Expense)], ['query']),
  'getExpensesByDateRange' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Vec(Expense)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const CashTransferCategory = IDL.Variant({
    'needToPay' : IDL.Null,
    'repay' : IDL.Null,
    'family' : IDL.Null,
  });
  const MedicalCategory = IDL.Variant({
    'hospital' : IDL.Null,
    'medicine' : IDL.Null,
  });
  const Category = IDL.Variant({
    'tea' : IDL.Null,
    'cashTransfer' : CashTransferCategory,
    'coolDrink' : IDL.Null,
    'petrol' : IDL.Null,
    'food' : IDL.Null,
    'trip' : IDL.Null,
    'others' : IDL.Null,
    'recharge' : IDL.Null,
    'bikeRepair' : IDL.Null,
    'fruits' : IDL.Null,
    'shopping' : IDL.Null,
    'medical' : MedicalCategory,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const Expense = IDL.Record({
    'id' : IDL.Nat,
    'subCategory' : IDL.Opt(IDL.Text),
    'date' : IDL.Text,
    'note' : IDL.Opt(IDL.Text),
    'repayName' : IDL.Opt(IDL.Text),
    'category' : Category,
    'amount' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addExpense' : IDL.Func(
        [
          IDL.Text,
          Category,
          IDL.Opt(IDL.Text),
          IDL.Nat,
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
        ],
        [IDL.Nat],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteExpense' : IDL.Func([IDL.Nat], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getExpenses' : IDL.Func([], [IDL.Vec(Expense)], ['query']),
    'getExpensesByDate' : IDL.Func([IDL.Text], [IDL.Vec(Expense)], ['query']),
    'getExpensesByDateRange' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(Expense)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };