/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type CashTransferCategory = { 'needToPay' : null } |
  { 'repay' : null } |
  { 'family' : null };
export type Category = { 'tea' : null } |
  { 'cashTransfer' : CashTransferCategory } |
  { 'coolDrink' : null } |
  { 'petrol' : null } |
  { 'food' : null } |
  { 'trip' : null } |
  { 'others' : null } |
  { 'recharge' : null } |
  { 'bikeRepair' : null } |
  { 'fruits' : null } |
  { 'shopping' : null } |
  { 'medical' : MedicalCategory };
export interface Expense {
  'id' : bigint,
  'subCategory' : [] | [string],
  'date' : string,
  'note' : [] | [string],
  'repayName' : [] | [string],
  'category' : Category,
  'amount' : bigint,
}
export type MedicalCategory = { 'hospital' : null } |
  { 'medicine' : null };
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addExpense' : ActorMethod<
    [string, Category, [] | [string], bigint, [] | [string], [] | [string]],
    bigint
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteExpense' : ActorMethod<[bigint], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getExpenses' : ActorMethod<[], Array<Expense>>,
  'getExpensesByDate' : ActorMethod<[string], Array<Expense>>,
  'getExpensesByDateRange' : ActorMethod<[string, string], Array<Expense>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];